# CriOS Default Configuration
# This file contains all default settings for the CriOS compound discovery system

processing:
  chunk_size: 1000
  parallel_workers: 4
  memory_limit: "4GB"
  batch_size: 500
  timeout_per_molecule: 10  # seconds
  
validation:
  strict_mode: true
  allow_stereochemistry: true
  remove_salts: true
  standardize: true
  allow_empty: false
  max_atoms: 200
  min_atoms: 1
  
descriptors:
  default:
    - MW
    - LogP
    - TPSA
    - HBA
    - HBD
    - RotatableBonds
  
  comprehensive:
    - MW
    - LogP
    - LogD
    - TPSA
    - HBA
    - HBD
    - RotatableBonds
    - AromaticRings
    - SaturatedRings
    - AliphaticRings
    - HeavyAtoms
    - QED
    - BertzCT
    - MolMR
    - FormalCharge
    - NumRadicals
    - NumHeteroatoms
    - FractionCsp3
    - NumSaturatedHeterocycles
    - NumAromaticHeterocycles
    - NumSpiroAtoms
    - NumBridgeheadAtoms
    - SASA
  
  qed:
    - MW
    - LogP
    - HBA
    - HBD
    - TPSA
    - RotatableBonds
    - AromaticRings
  
filters:
  lipinski:
    MW: [null, 500]
    LogP: [null, 5]
    HBD: [null, 5]
    HBA: [null, 10]
  
  lead_like:
    MW: [200, 350]
    LogP: [-1, 3]
    HBD: [null, 3]
    HBA: [null, 7]
    RotatableBonds: [null, 7]
  
  fragment:
    MW: [null, 300]
    LogP: [null, 3]
    HBD: [null, 3]
    HBA: [null, 3]
    RotatableBonds: [null, 3]
  
  drug_like:
    MW: [150, 500]
    LogP: [-2, 5]
    HBD: [null, 5]
    HBA: [null, 10]
    TPSA: [null, 140]
    RotatableBonds: [null, 10]
  
  ro3:  # Rule of Three
    MW: [null, 300]
    LogP: [null, 3]
    HBD: [null, 3]
    HBA: [null, 3]
    RotatableBonds: [null, 3]
  
  pains:  # Pan-Assay Interference Compounds
    enabled: true
    strict: false
  
similarity:
  default_method: "morgan"
  morgan_radius: 2
  morgan_nbits: 2048
  tanimoto_threshold: 0.7
  dice_threshold: 0.7
  
clustering:
  default_method: "butina"
  butina_threshold: 0.4
  kmeans_clusters: 10
  hierarchical_linkage: "average"
  
database:
  default_backend: "sqlite"
  sqlite:
    path: "compound_library.db"
    timeout: 30
  postgresql:
    host: "localhost"
    port: 5432
    database: "crios"
    user: "crios_user"
    connection_pool_size: 10
  
api:
  pubchem:
    base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
    timeout: 30
    retry_count: 3
    retry_delay: 1
    max_compounds_per_request: 100
  
  chembl:
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    timeout: 30
    retry_count: 3
    retry_delay: 1
    page_size: 100
  
  zinc:
    base_url: "https://zinc.docking.org/api"
    timeout: 30
    retry_count: 3
  
output:
  default_format: "csv"
  csv:
    delimiter: ","
    include_header: true
    float_precision: 4
  
  json:
    indent: 2
    sort_keys: true
    include_metadata: true
  
  sdf:
    kekulize: false
    include_properties: true
  
  smiles:
    canonical: true
    delimiter: "\t"
    include_id: true
  
logging:
  level: "INFO"
  file: "crios.log"
  format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
  console:
    enabled: true
    colorize: true
  
  rotation:
    max_bytes: 10485760  # 10MB
    backup_count: 5
  
performance:
  cache:
    enabled: true
    max_size: 1000
    ttl: 3600  # seconds
  
  multiprocessing:
    enabled: true
    max_workers: null  # None means use all available cores
    chunk_size: 100
  
  memory:
    monitor: true
    max_usage_percent: 80
    gc_threshold: 100  # MB
  
visualization:
  molecule:
    size: [300, 300]
    kekulize: true
    highlight_atoms: []
    highlight_bonds: []
  
  plot:
    dpi: 100
    figure_size: [10, 6]
    style: "seaborn"
    colormap: "viridis"