# CriOS Discovery Engine - Ethical AI Policy Framework
# "Science before status. Discovery before profit. Earth and people above extraction."

# Core Ethical Principles
principles:
  mission_statement: "Regenerative discovery system rooted in ethical science, designed to realign health, ecology, and industry with nature's principles"
  
  core_values:
    - "Science before status"
    - "Discovery before profit"
    - "Earth and people above extraction"
    - "Healing over harm"
    - "Transparency over trade secrets"
    - "Collaboration over competition"

# Discovery Ethics Framework
discovery_ethics:
  # Research Priorities
  research_priorities:
    primary:
      - neurodegeneration_therapeutics
      - environmental_health
      - regenerative_medicine
      - sustainable_materials
    secondary:
      - aging_research
      - metabolic_disorders
      - natural_product_optimization
    
  excluded_applications:
    - biological_weapons
    - environmental_damage
    - addictive_substances
    - predatory_pricing_models

# AI Safety & Alignment
ai_safety:
  # Human-in-the-Loop Requirements
  human_oversight:
    required_for:
      - novel_compound_generation
      - safety_predictions
      - therapeutic_recommendations
      - patent_analysis
    validation_threshold: 0.95
    expert_review_required: true
    
  # Bias Prevention
  bias_mitigation:
    training_data_diversity: true
    fairness_metrics: ["demographic_parity", "equalized_odds"]
    bias_auditing_frequency: "monthly"
    
  # Transparency Requirements
  transparency:
    model_interpretability: "required"
    decision_explanations: "detailed"
    uncertainty_quantification: true
    confidence_intervals: true

# Data Ethics & Privacy
data_ethics:
  # Data Sources
  approved_sources:
    public_databases:
      - chembl
      - pubchem
      - drugbank
      - zinc
    literature:
      - pubmed
      - patent_databases
      - scientific_journals
      
  prohibited_sources:
    - proprietary_without_permission
    - personally_identifiable_data
    - military_classified_data
    
  # Data Usage Principles
  usage_principles:
    attribution_required: true
    open_access_preferred: true
    commercial_restrictions_respected: true
    privacy_preserving: true

# Compound Classification Ethics
compound_ethics:
  # Safety Classifications
  safety_categories:
    green: "Safe for general research and development"
    yellow: "Requires additional safety assessment"
    red: "Restricted or prohibited compounds"
    
  # Dual-Use Research Oversight
  dual_use:
    screening_required: true
    review_committee: "CriOS Ethics Board"
    restricted_compounds:
      - chemical_weapons_precursors
      - controlled_substances
      - environmental_toxins
      
  # Natural Product Ethics
  natural_products:
    indigenous_knowledge_respect: true
    biopiracy_prevention: true
    fair_benefit_sharing: true
    source_attribution: required

# Intellectual Property Ethics
ip_ethics:
  # Mission-Locked IP Structure
  mission_lock:
    enabled: true
    ethical_licensing_required: true
    public_benefit_clause: true
    profit_cap_percentage: 15
    
  # Patent Strategy
  patents:
    defensive_only: false
    open_licensing_preferred: true
    fair_licensing_terms: true
    research_exemptions: true
    
  # Publication Policy
  publication:
    preprint_encouraged: true
    open_access_preferred: true
    methodology_transparency: "complete"
    negative_results_published: true

# Environmental & Social Impact
impact_assessment:
  # Environmental Considerations
  environmental:
    lifecycle_assessment: true
    biodegradability_preferred: true
    green_chemistry_principles: true
    carbon_footprint_minimization: true
    
  # Social Impact
  social:
    accessibility_prioritized: true
    global_south_considerations: true
    healthcare_equity: true
    community_benefit_focus: true

# Collaboration & Sharing
collaboration:
  # Academic Partnerships
  academic:
    knowledge_sharing: "encouraged"
    joint_research: "prioritized"
    student_involvement: "supported"
    
  # Industry Engagement
  industry:
    ethical_partnerships_only: true
    mission_alignment_required: true
    profit_sharing_fair: true
    
  # Global Health
  global_health:
    developing_nations_access: "prioritized"
    neglected_diseases: "included"
    affordability_targets: true

# Quality & Integrity
quality_standards:
  # Scientific Rigor
  scientific:
    reproducibility_required: true
    peer_review_encouraged: true
    statistical_significance: true
    multiple_validation: true
    
  # Data Integrity
  data_integrity:
    version_control: "mandatory"
    audit_trails: "complete"
    error_correction: "transparent"
    quality_metrics: "tracked"

# Enforcement & Governance
governance:
  # Ethics Review Board
  review_board:
    composition: ["ethicist", "scientist", "community_representative"]
    review_frequency: "quarterly"
    decision_authority: "binding"
    appeal_process: "available"
    
  # Compliance Monitoring
  compliance:
    automated_screening: true
    human_review_required: true
    violation_reporting: "mandatory"
    corrective_actions: "documented"
    
  # Continuous Improvement
  improvement:
    policy_updates: "annual"
    stakeholder_feedback: "quarterly"
    best_practices_integration: true
    ethics_training: "required"

# Reporting & Accountability
accountability:
  # Regular Reporting
  reporting:
    ethics_dashboard: "public"
    annual_impact_report: true
    transparency_metrics: "tracked"
    community_updates: "monthly"
    
  # Violation Response
  violations:
    investigation_process: "formal"
    corrective_measures: "proportional"
    prevention_strategies: "implemented"
    public_disclosure: "when_appropriate"

# Emergency Protocols
emergency:
  # Safety Incidents
  safety_incidents:
    immediate_halt: true
    expert_consultation: "mandatory"
    regulatory_notification: "required"
    public_communication: "transparent"
    
  # Ethical Concerns
  ethical_concerns:
    whistleblower_protection: true
    independent_investigation: true
    stakeholder_notification: true
    remediation_plan: "required"